-- NPP-192 Option 1 rebuilt from the seed (reference document §4 and §6.2).
-- Runs after 14, which leaves the seed in the database. Every priced line of
-- the workbook's OPTION1 sheet is added: catalogue parts as free components,
-- the eleven uncatalogued lines typed in at the workbook price.

\set alpha  '00000000-0000-0000-0000-0000000000c2'
\set alice  '00000000-0000-0000-0000-0000000000a2'
\set carol  '00000000-0000-0000-0000-0000000000a4'

-- The workbook has no discount, no uplift and rounds up to 100; margins are set
-- per costing below. Company settings are frozen at creation, so set them first.
update public.companies
   set discount_pct = 0, material_margin_pct = 0, labour_margin_pct = 0,
       enclosure_uplift_pct = 0, price_rounding_step = 100, tax_pct = 16, exchange_rate = 1
 where id = :'alpha'::uuid;

begin;
set local role authenticated;
select test.sign_in(:'carol');
select id as costing_id from app.create_costing('NPP-192 Option 1, from the seed') \gset
insert into public.costing_panels (costing_id, company_id, name, quantity, uom, option_label)
values (:'costing_id'::uuid, :'alpha'::uuid, 'MAIN LV BOARD', 1, 'PC', 'Option 1')
returning id as panel_id \gset

-- generated by: python3 scripts/check_npp192.py OPTION1 --sql
select app.add_component_to_costing(:'panel_id'::uuid, (select id from public.components where company_id is null and upper(code) = '3WJ1116-2AE42-4DD0-Z F40+R55+T40'), 1);  -- INCOMER
select app.add_component_to_costing(:'panel_id'::uuid, (select id from public.components where company_id is null and upper(code) = '3WJ1108-2AE12-4DD0-Z F40+S55+T40'), 2);  -- INCOMER
select app.add_component_to_costing(:'panel_id'::uuid, (select id from public.components where company_id is null and upper(code) = 'LOGO'), 1);  -- ATS CONTROLS
select app.add_manual_item(:'panel_id'::uuid, 'SYNCHRO CHECK RELAYS', 'switchgear', 35000.00, 2);  -- ATS CONTROLS
select app.add_manual_item(:'panel_id'::uuid, 'CONTROLS', 'switchgear', 60000.00, 1);  -- ATS CONTROLS
select app.add_manual_item(:'panel_id'::uuid, '1600/5A CT', 'switchgear', 4200.00, 4);  -- ATS CONTROLS
select app.add_manual_item(:'panel_id'::uuid, '800/5A CT', 'switchgear', 4200.00, 8);  -- ATS CONTROLS
select app.add_component_to_costing(:'panel_id'::uuid, (select id from public.components where company_id is null and upper(code) = '3WJ1116-2AE02-1AD0'), 1);  -- SOLAR INCOMING  SECTION
select app.add_component_to_costing(:'panel_id'::uuid, (select id from public.components where company_id is null and upper(code) = '3SB5285-6HC03'), 5);  -- ACCESSORIES
select app.add_component_to_costing(:'panel_id'::uuid, (select id from public.components where company_id is null and upper(code) = '3SB5285-6HD03'), 5);  -- ACCESSORIES
select app.add_component_to_costing(:'panel_id'::uuid, (select id from public.components where company_id is null and upper(code) = '3SB5285-6HF03'), 5);  -- ACCESSORIES
select app.add_component_to_costing(:'panel_id'::uuid, (select id from public.components where company_id is null and upper(code) = '5TJ6106-7'), 22);  -- ACCESSORIES
select app.add_component_to_costing(:'panel_id'::uuid, (select id from public.components where company_id is null and upper(code) = 'LM1340'), 3);  -- ACCESSORIES
select app.add_manual_item(:'panel_id'::uuid, '1600/5A CT', 'switchgear', 4200.00, 3);  -- ACCESSORIES
select app.add_manual_item(:'panel_id'::uuid, '800/5A CT', 'switchgear', 3200.00, 6);  -- ACCESSORIES
select app.add_component_to_costing(:'panel_id'::uuid, (select id from public.components where company_id is null and upper(code) = 'EBS2U'), 1);  -- ACCESSORIES
select app.add_component_to_costing(:'panel_id'::uuid, (select id from public.components where company_id is null and upper(code) = 'RT18-125/RO17'), 1);  -- ACCESSORIES
select app.add_manual_item(:'panel_id'::uuid, '3WJ1108-2AE02-1AD1', 'switchgear', 171562.00, 1);  -- APFC BANK-400 KVAR
select app.add_component_to_costing(:'panel_id'::uuid, (select id from public.components where company_id is null and upper(code) = 'RPCF-16'), 1);  -- APFC BANK-400 KVAR
select app.add_component_to_costing(:'panel_id'::uuid, (select id from public.components where company_id is null and upper(code) = 'ZJE500TP480V'), 4);  -- APFC BANK-400 KVAR
select app.add_component_to_costing(:'panel_id'::uuid, (select id from public.components where company_id is null and upper(code) = 'ZJE250TP480V'), 4);  -- APFC BANK-400 KVAR
select app.add_component_to_costing(:'panel_id'::uuid, (select id from public.components where company_id is null and upper(code) = 'ZJE125TP480V'), 6);  -- APFC BANK-400 KVAR
select app.add_component_to_costing(:'panel_id'::uuid, (select id from public.components where company_id is null and upper(code) = 'ZJE005TP480V'), 5);  -- APFC BANK-400 KVAR
select app.add_component_to_costing(:'panel_id'::uuid, (select id from public.components where company_id is null and upper(code) = 'CSTC1D50K12U5'), 4);  -- APFC BANK-400 KVAR
select app.add_component_to_costing(:'panel_id'::uuid, (select id from public.components where company_id is null and upper(code) = 'TC1D25K11U5'), 4);  -- APFC BANK-400 KVAR
select app.add_component_to_costing(:'panel_id'::uuid, (select id from public.components where company_id is null and upper(code) = 'CSTC1D16K11U5'), 6);  -- APFC BANK-400 KVAR
select app.add_component_to_costing(:'panel_id'::uuid, (select id from public.components where company_id is null and upper(code) = 'CSTC1D05K10U5'), 5);  -- APFC BANK-400 KVAR
select app.add_component_to_costing(:'panel_id'::uuid, (select id from public.components where company_id is null and upper(code) = 'CSCDFL00125'), 12);  -- APFC BANK-400 KVAR
select app.add_component_to_costing(:'panel_id'::uuid, (select id from public.components where company_id is null and upper(code) = 'NH00-50A'), 12);  -- APFC BANK-400 KVAR
select app.add_component_to_costing(:'panel_id'::uuid, (select id from public.components where company_id is null and upper(code) = 'NH00-32A'), 18);  -- APFC BANK-400 KVAR
select app.add_component_to_costing(:'panel_id'::uuid, (select id from public.components where company_id is null and upper(code) = 'NH00-16A'), 15);  -- APFC BANK-400 KVAR
select app.add_component_to_costing(:'panel_id'::uuid, (select id from public.components where company_id is null and upper(code) = 'DNTRS-160/3'), 19);  -- APFC BANK-400 KVAR
select app.add_component_to_costing(:'panel_id'::uuid, (select id from public.components where company_id is null and upper(code) = 'DN01479'), 19);  -- APFC BANK-400 KVAR
select app.add_manual_item(:'panel_id'::uuid, 'TIMERS AND RELAYS', 'switchgear', 3000.00, 6);  -- APFC BANK-400 KVAR
select app.add_manual_item(:'panel_id'::uuid, '1600/5A CT', 'switchgear', 7200.00, 1);  -- APFC BANK-400 KVAR
select app.add_manual_item(:'panel_id'::uuid, 'FK5526-230', 'switchgear', 7875.00, 2);  -- APFC BANK-400 KVAR
select app.add_component_to_costing(:'panel_id'::uuid, (select id from public.components where company_id is null and upper(code) = '35SQMM'), 90);  -- APFC BANK-400 KVAR
select app.add_component_to_costing(:'panel_id'::uuid, (select id from public.components where company_id is null and upper(code) = '16SQMM'), 30);  -- APFC BANK-400 KVAR
select app.add_component_to_costing(:'panel_id'::uuid, (select id from public.components where company_id is null and upper(code) = '3VJ1463-5DB32-0AA0'), 1);  -- OUTGOERS
select app.add_component_to_costing(:'panel_id'::uuid, (select id from public.components where company_id is null and upper(code) = '3VJ1340-5DB32-0AA0'), 3);  -- OUTGOERS
select app.add_component_to_costing(:'panel_id'::uuid, (select id from public.components where company_id is null and upper(code) = '3VJ1225-3DB32-0AA0'), 6);  -- OUTGOERS
select app.add_component_to_costing(:'panel_id'::uuid, (select id from public.components where company_id is null and upper(code) = '3VJ1216-3DB32-0AA0'), 3);  -- OUTGOERS
select app.add_component_to_costing(:'panel_id'::uuid, (select id from public.components where company_id is null and upper(code) = '3VJ1012-3DB32-0AA0'), 3);  -- OUTGOERS
select app.add_component_to_costing(:'panel_id'::uuid, (select id from public.components where company_id is null and upper(code) = '50X10MM'), 30);  -- BUSBAR
select app.add_component_to_costing(:'panel_id'::uuid, (select id from public.components where company_id is null and upper(code) = '40X10MM'), 18);  -- BUSBAR
select app.add_component_to_costing(:'panel_id'::uuid, (select id from public.components where company_id is null and upper(code) = '30X10MM'), 13);  -- BUSBAR
select app.add_component_to_costing(:'panel_id'::uuid, (select id from public.components where company_id is null and upper(code) = '20X10MM'), 77);  -- BUSBAR
select app.add_component_to_costing(:'panel_id'::uuid, (select id from public.components where company_id is null and upper(code) = '40X5MM'), 8);  -- BUSBAR
select app.add_component_to_costing(:'panel_id'::uuid, (select id from public.components where company_id is null and upper(code) = '70SQMM'), 18);  -- BUSBAR
select app.add_component_to_costing(:'panel_id'::uuid, (select id from public.components where company_id is null and upper(code) = '50SQMM'), 9);  -- BUSBAR
select app.add_component_to_costing(:'panel_id'::uuid, (select id from public.components where company_id is null and upper(code) = '35SQMM'), 9);  -- BUSBAR
select app.add_manual_item(:'panel_id'::uuid, '4000', 'enclosure_parts', 408000.00, 1);  -- ENCLOSURE

select test.eq((select count(*) from public.costing_assemblies where costing_id = :'costing_id'::uuid), 1::bigint,
  'everything sits in the panel''s one components-and-enclosure line');
select test.eq((select kind from public.costing_assemblies where costing_id = :'costing_id'::uuid), 'free',
  'which is the free holder');

-- The §6.2 material figure, to the cent.
select test.eq((select material_cost from public.v_costing_panel_costs where costing_id = :'costing_id'::uuid),
               4012709.80, 'material for Option 1 from the seed is 4,012,709.80 (workbook 4,164,997.80; §6.2 explains the gap)');

-- By category. The workbook files 106,800 of cable under its APFC section; the
-- app files cable under busbar & cable, so its split differs by that amount.
select test.eq((select sum(line_total) from public.v_costing_items_by_category
                where costing_id = :'costing_id'::uuid and category_code = 'switchgear'), 2279621.80,
  'switchgear 2,279,621.80 (= §6.2 2,386,421.80 less 106,800 of cable filed under busbar)');
select test.eq((select sum(line_total) from public.v_costing_items_by_category
                where costing_id = :'costing_id'::uuid and category_code = 'busbar'), 1325088.00,
  'busbar & cable 1,325,088.00 (= §6.2 1,218,288.00 plus that cable)');
select test.eq((select sum(line_total) from public.v_costing_items_by_category
                where costing_id = :'costing_id'::uuid and category_code = 'enclosure_parts'), 408000.00,
  'enclosure 408,000.00, typed in as the workbook has it');

-- Individual workings kept on the lines.
select test.eq((select unit_price from public.costing_items where costing_id = :'costing_id'::uuid and code = '50X10MM'),
               13440.00, 'busbar 50 x 10 is 4.48 kg × 3,000 = 13,440 per metre');
select test.eq((select quantity from public.costing_items where costing_id = :'costing_id'::uuid and code = '35SQMM'),
               99.000, 'the same cable added twice adds up (90 + 9 m)');
select test.eq((select count(*) from public.costing_items where costing_id = :'costing_id'::uuid and is_manual)::int, 11,
  'eleven typed lines');
select test.eq((select landed_factor from public.costing_items where costing_id = :'costing_id'::uuid and code = 'LOGO'),
               1.76991150, 'a catalogue line keeps the factor that priced it');

-- With no margin the panel price is the material rounded up to 100.
select test.eq((select unit_price from public.v_costing_panel_prices where costing_id = :'costing_id'::uuid),
               4012800.00, 'rounded up to the next 100');
commit;

-- === The workbook's arithmetic on its own material figure ==================
-- ÷ 0.8 then ÷ 0.9 is one margin of 28 % in the app's terms (the app has no
-- labour-as-a-percentage). Then round up to 100, then VAT.
update public.companies set material_margin_pct = 28 where id = :'alpha'::uuid;

begin;
set local role authenticated;
select test.sign_in(:'carol');
select id as costing_id from app.create_costing('NPP-192 arithmetic check') \gset
insert into public.costing_panels (costing_id, company_id, name, quantity, uom)
values (:'costing_id'::uuid, :'alpha'::uuid, 'MAIN LV BOARD', 1, 'PC') returning id as panel_id \gset
select app.add_manual_item(:'panel_id'::uuid, 'Workbook material', 'switchgear', 4164997.80, 1);

select test.eq((select material_sell from public.v_costing_panel_prices where costing_id = :'costing_id'::uuid),
               5784719.17, '4,164,997.80 ÷ 0.72 = 5,784,719.17');
select test.eq((select unit_price from public.v_costing_panel_prices where costing_id = :'costing_id'::uuid),
               5784800.00, 'rounded up to 100: 5,784,800, the workbook''s TOTAL (KES)');
select test.eq((select tax from public.v_costing_totals where costing_id = :'costing_id'::uuid),
               925568.00, 'VAT 16 %: 925,568.00');
select test.eq((select grand_total from public.v_costing_totals where costing_id = :'costing_id'::uuid),
               6710368.00, 'total 6,710,368.00, as quoted');

update public.costings set negotiation_margin_pct = 5 where id = :'costing_id'::uuid;
select test.eq((select unit_price from public.v_costing_panel_prices where costing_id = :'costing_id'::uuid),
               6089200.00, 'a 5 % negotiation margin: 5,784,719.17 ÷ 0.95 rounded up to 100');
rollback;

update public.companies set material_margin_pct = 0 where id = :'alpha'::uuid;

-- === Free lines behave =====================================================
begin;
set local role authenticated;
select test.sign_in(:'carol');
select id as costing_id from app.create_costing('Free lines') \gset
insert into public.costing_panels (costing_id, company_id, name, quantity, uom)
values (:'costing_id'::uuid, :'alpha'::uuid, 'Board', 1, 'PC') returning id as panel_id \gset
select app.add_component_to_costing(:'panel_id'::uuid, (select id from public.components where company_id is null and code = '800(W)X800(D)X2100(H)-2B'), 2);
select app.add_manual_item(:'panel_id'::uuid, 'Timers', 'switchgear', 3000, 6);
select test.eq((select count(*) from public.costing_assemblies where panel_id = :'panel_id'::uuid)::int, 1,
  'one holder for both the cubicle and the typed line');
select test.refuses(
  format('update public.costing_assemblies set quantity = 2 where panel_id = %L and kind = ''free''', :'panel_id'),
  'the holder''s quantity cannot change', 'always has quantity 1');
select test.eq((select code from public.costing_items where costing_id = :'costing_id'::uuid and is_manual), 'MANUAL-001',
  'typed lines are numbered');
select test.refuses(
  format('select app.add_manual_item(%L, ''X'', ''widgets'', 1, 1)', :'panel_id'),
  'a typed line needs one of the four categories', 'unknown category');
rollback;

-- The uplift reaches a free cubicle too.
update public.companies set enclosure_uplift_pct = 10 where id = :'alpha'::uuid;
begin;
set local role authenticated;
select test.sign_in(:'carol');
select id as costing_id from app.create_costing('Uplift') \gset
insert into public.costing_panels (costing_id, company_id, name, quantity, uom)
values (:'costing_id'::uuid, :'alpha'::uuid, 'Board', 1, 'PC') returning id as panel_id \gset
select app.add_component_to_costing(:'panel_id'::uuid, (select id from public.components where company_id is null and code = '800(W)X800(D)X2100(H)-2B'), 1);
-- 380 EUR × 200 = 76,000, plus 10 %.
select test.eq((select unit_price from public.costing_items where costing_id = :'costing_id'::uuid), 83600.00,
  'a cubicle added on its own is uplifted like one inside a kit');
select test.eq((select uplift_pct from public.costing_items where costing_id = :'costing_id'::uuid), 10.000,
  'and the uplift is kept on the line');
rollback;
update public.companies set enclosure_uplift_pct = 0 where id = :'alpha'::uuid;

-- === A kit from the seed, by the picker's path ==============================
begin;
set local role authenticated;
select test.sign_in(:'carol');
select id as kit_id from public.v_kits where code = app.kit_code('250A,TP,MCCB, Adjustable, 25KA-KIT') \gset
select test.eq((select group_name from public.v_kits where id = :'kit_id'), 'MCCB', 'the picker sees the kit''s group');
select test.eq((select main_device_code from public.v_kits where id = :'kit_id'), '3VJ1225-3DB32-0AA0', 'and its main device');
select test.eq((select has_unpriced_part from public.v_kits where id = :'kit_id'), false, 'and that every line is priced');
select test.eq((select has_unpriced_part from public.v_kits where code = app.kit_code('PLACEHOLDER KIT')), true,
  'while a kit on a placeholder is marked');

select id as costing_id from app.create_costing('Kit by rating') \gset
insert into public.costing_panels (costing_id, company_id, name, quantity, uom)
values (:'costing_id'::uuid, :'alpha'::uuid, 'Board', 1, 'PC') returning id as panel_id \gset
select app.add_assembly_to_costing(:'panel_id'::uuid, :'kit_id'::uuid, 1);
-- 250A MCCB 99.52 EUR × 200 = 19,904.00; 3 m of 95 mm² cable at 13.85 × 200 = 2,770 each.
select test.eq((select material_each from public.v_costing_assembly_totals where costing_id = :'costing_id'::uuid),
               28214.00, 'the kit prices to the sum of its lines');
select test.eq((select hours from public.costing_labour where costing_id = :'costing_id'::uuid and process_type = 'assembly'),
               2.00, 'with the kit group''s hours (set in test 14)');
rollback;

-- === A revision keeps every frozen column ==================================
begin;
set local role authenticated;
select test.sign_in(:'carol');
select id as costing_id from app.create_costing('Revision keeps workings') \gset
insert into public.costing_panels (costing_id, company_id, name, quantity, uom)
values (:'costing_id'::uuid, :'alpha'::uuid, 'Board', 1, 'PC') returning id as panel_id \gset
select app.add_component_to_costing(:'panel_id'::uuid, (select id from public.components where company_id is null and code = 'LOGO'), 1);
select app.add_manual_item(:'panel_id'::uuid, 'Controls', 'switchgear', 60000, 1);
select app.submit_costing(:'costing_id'::uuid);
commit;
begin;
set local role authenticated;
select test.sign_in(:'alice');
select app.approve_costing(:'costing_id'::uuid);
commit;
begin;
set local role authenticated;
select test.sign_in(:'carol');
select id as rev_id from app.create_costing_revision(:'costing_id'::uuid) \gset
select test.eq((select count(*) from public.costing_items where costing_id = :'rev_id'::uuid)::int, 2, 'both lines are copied');
select test.eq((select landed_factor from public.costing_items where costing_id = :'rev_id'::uuid and code = 'LOGO'),
               (select landed_factor from public.costing_items where costing_id = :'costing_id'::uuid and code = 'LOGO'),
  'the landed factor survives the revision');
select test.eq((select purchase_price from public.costing_items where costing_id = :'rev_id'::uuid and code = 'LOGO'), 154.0000,
  'so does the purchase price');
select test.eq((select is_manual from public.costing_items where costing_id = :'rev_id'::uuid and code = 'MANUAL-001'), true,
  'and a typed line stays typed');
select test.eq((select kind from public.costing_assemblies where costing_id = :'rev_id'::uuid), 'free',
  'and the holder stays a holder');
rollback;
delete from public.costings where title = 'Revision keeps workings';
