import type { WordDocument } from './word'

/**
 * Writing the `.docx`. The `docx` library is loaded **on demand**, as exceljs and
 * the PDF renderer are, so its weight is only fetched when somebody actually
 * exports a technical offer.
 *
 * This module is the only one that knows about the library. Everything about what
 * the document says is decided in `word.ts` and tested there.
 */
export async function downloadWordDocument(document_: WordDocument): Promise<void> {
  const { Document, HeadingLevel, Packer, Paragraph, TextRun } = await import('docx')

  const children = document_.blocks.map((block) => {
    switch (block.kind) {
      case 'title':
        return new Paragraph({ text: block.text, heading: HeadingLevel.HEADING_1 })
      case 'meta':
        return new Paragraph({
          children: [
            new TextRun({ text: `${block.label}: `, bold: true }),
            new TextRun({ text: block.value }),
          ],
          spacing: { after: 60 },
        })
      case 'heading':
        return new Paragraph({ text: block.text, heading: HeadingLevel.HEADING_2, spacing: { before: 240 } })
      case 'panel':
        return new Paragraph({
          children: [
            new TextRun({ text: `${block.srNo}. ${block.particular}`, bold: true }),
            new TextRun({ text: `   (qty ${block.qty})` }),
          ],
          heading: HeadingLevel.HEADING_2,
          spacing: { before: 280, after: 80 },
        })
      default:
        return new Paragraph({ text: block.text, spacing: { after: 120 } })
    }
  })

  const blob = await Packer.toBlob(
    new Document({
      title: document_.title,
      description: 'Technical offer generated by CostMatrix',
      sections: [{ children }],
    }),
  )
  save(blob, document_.fileName)
}

function save(blob: Blob, fileName: string): void {
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = fileName
  a.click()
  URL.revokeObjectURL(url)
}
