import type { PdfTechnicalRow } from './pdf/types'

/**
 * The technical offer as an editable Word document (roadmap 4.3).
 *
 * The owner's engineers want to take the generated technical offer, edit a
 * sentence and send it. A PDF cannot be edited, so this writes a real `.docx`.
 *
 * The **structure is built here as plain data** and the `docx` library is used
 * only to turn it into a file (`word-io.ts`), which is the pattern the quotation
 * PDF already follows: everything that decides content is testable without
 * rendering anything.
 */

export interface WordJob {
  companyName: string
  costingNo: string
  revisionNo: number
  title: string
  customerName: string | null
  dateLong: string
  eplanProject: string | null
  drawingNumbers: string[]
}

/** A paragraph of the document: a heading, body text, or a row of the table. */
export type WordBlock =
  | { kind: 'title'; text: string }
  | { kind: 'meta'; label: string; value: string }
  | { kind: 'heading'; text: string }
  | { kind: 'body'; text: string }
  | { kind: 'panel'; srNo: number; particular: string; qty: string }

export interface WordDocument {
  fileName: string
  title: string
  blocks: WordBlock[]
}

/**
 * The document, block by block. One section per panel rather than one big table,
 * because a person editing this wants to type into prose, not into a cell — and
 * the technical description is already paragraphs.
 */
export function buildWordDocument(rows: PdfTechnicalRow[], job: WordJob): WordDocument {
  const blocks: WordBlock[] = [
    { kind: 'title', text: 'DETAILED TECHNICAL OFFER' },
    { kind: 'meta', label: 'Costing', value: `${job.costingNo} REV${job.revisionNo}` },
    { kind: 'meta', label: 'Job', value: job.title },
  ]

  if (job.customerName !== null && job.customerName.trim() !== '') {
    blocks.push({ kind: 'meta', label: 'Customer', value: job.customerName })
  }
  if (job.eplanProject !== null && job.eplanProject.trim() !== '') {
    blocks.push({ kind: 'meta', label: 'EPLAN project', value: job.eplanProject })
  }
  if (job.drawingNumbers.length > 0) {
    blocks.push({ kind: 'meta', label: 'Drawing numbers', value: job.drawingNumbers.join(', ') })
  }
  blocks.push({ kind: 'meta', label: 'Date', value: job.dateLong })

  if (rows.length === 0) {
    blocks.push({
      kind: 'body',
      text: 'This costing has no panels yet, so there is nothing to describe.',
    })
    return { fileName: fileName(job), title: documentTitle(job), blocks }
  }

  for (const row of rows) {
    blocks.push({ kind: 'panel', srNo: row.srNo, particular: row.particular, qty: row.qty })
    // The description arrives as paragraphs separated by blank lines; each one
    // becomes a Word paragraph so it can be edited like any other.
    const paragraphs = row.description.split(/\n{2,}/).map((p) => p.trim()).filter(Boolean)
    if (paragraphs.length === 0) {
      blocks.push({ kind: 'body', text: '—' })
    } else {
      for (const paragraph of paragraphs) {
        blocks.push({ kind: 'body', text: paragraph.replace(/\n/g, ' ') })
      }
    }
  }

  blocks.push({ kind: 'heading', text: 'Notes' })
  blocks.push({
    kind: 'body',
    text: `Generated by CostMatrix from ${job.costingNo} REV${job.revisionNo} on ${job.dateLong}. Edit freely: this document is a copy, and nothing typed here changes the costing or the quotation.`,
  })

  return { fileName: fileName(job), title: documentTitle(job), blocks }
}

export function documentTitle(job: WordJob): string {
  return `${job.costingNo} REV${job.revisionNo} — technical offer`
}

export function fileName(job: WordJob): string {
  return `${job.costingNo}-REV${job.revisionNo}-technical-offer.docx`
}

/** Drawing numbers as the costing keeps them: one per line, or comma-separated. */
export function splitDrawings(text: string | null): string[] {
  if (text === null) return []
  return text
    .split(/[\r\n,;]+/)
    .map((d) => d.trim())
    .filter(Boolean)
}
